// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7otV59m9yfjtz0bzuJjJJczGMRHwunkI',
    appId: '1:796094377986:web:d893b42ab39fff7915b71b',
    messagingSenderId: '796094377986',
    projectId: 'geoab-779d7',
    authDomain: 'geoab-779d7.firebaseapp.com',
    storageBucket: 'geoab-779d7.appspot.com',
    measurementId: 'G-3WNK402WXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-ZgAxZPi77GNP3GhbB5H0_5TFyMBMrw',
    appId: '1:796094377986:android:3b021b54cb6a096615b71b',
    messagingSenderId: '796094377986',
    projectId: 'geoab-779d7',
    storageBucket: 'geoab-779d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZzN7R072kT3uEBdmFa03PfXb83TPVw6o',
    appId: '1:796094377986:ios:463dfbe292d906df15b71b',
    messagingSenderId: '796094377986',
    projectId: 'geoab-779d7',
    storageBucket: 'geoab-779d7.appspot.com',
    iosBundleId: 'br.edu.ifg.geoab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZzN7R072kT3uEBdmFa03PfXb83TPVw6o',
    appId: '1:796094377986:ios:e267b7d765e3e87b15b71b',
    messagingSenderId: '796094377986',
    projectId: 'geoab-779d7',
    storageBucket: 'geoab-779d7.appspot.com',
    iosBundleId: 'br.edu.ifg.geoab.RunnerTests',
  );
}
